language: node_js

node_js: 
  - "12"

script: echo "Running tests against $(node -v)..."

before_script:
  - export TZ='Europe/Amsterdam'
  - npm install
script:
  - npm run test
  - npm run lint
after_success: 'npm run report-coverage'
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_TOKEN"
  on:
    tags: true
    branch: master
  edge: true
